# Generated by Django 5.1.4 on 2025-04-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airlineid', models.CharField(db_column='airlineID', max_length=50, primary_key=True, serialize=False)),
                ('revenue', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'airline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airportid', models.CharField(db_column='airportID', max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'airport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.CharField(db_column='flightID', max_length=50, primary_key=True, serialize=False)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('airplane_status', models.CharField(blank=True, max_length=100, null=True)),
                ('next_time', models.TimeField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('legid', models.CharField(db_column='legID', max_length=50, primary_key=True, serialize=False)),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'leg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.CharField(db_column='locationID', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44AutogradingHighLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_tag', models.CharField(blank=True, max_length=1, null=True)),
                ('score_category', models.CharField(blank=True, max_length=100, null=True)),
                ('total_possible', models.DecimalField(blank=True, decimal_places=0, max_digits=42, null=True)),
                ('total_passed', models.DecimalField(blank=True, decimal_places=0, max_digits=42, null=True)),
            ],
            options={
                'db_table': 'magic44_autograding_high_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44AutogradingLowLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_label', models.CharField(blank=True, max_length=20, null=True)),
                ('query_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_cases', models.BigIntegerField()),
                ('passed_cases', models.BigIntegerField()),
            ],
            options={
                'db_table': 'magic44_autograding_low_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44AutogradingQueryLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_status_category', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_affected', models.BigIntegerField(blank=True, null=True)),
                ('queries_affected', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'magic44_autograding_query_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44AutogradingScoreSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_label', models.CharField(blank=True, max_length=20, null=True)),
                ('query_name', models.CharField(blank=True, max_length=100, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=55, null=True)),
                ('scoring_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'magic44_autograding_score_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44ColumnErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('step_id', models.IntegerField()),
                ('category', models.CharField(max_length=7)),
                ('row_hash', models.TextField()),
            ],
            options={
                'db_table': 'magic44_column_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44DataCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepid', models.IntegerField(blank=True, db_column='stepID', null=True)),
                ('queryid', models.IntegerField(blank=True, db_column='queryID', null=True)),
                ('columndump0', models.CharField(blank=True, db_column='columnDump0', max_length=1000, null=True)),
                ('columndump1', models.CharField(blank=True, db_column='columnDump1', max_length=1000, null=True)),
                ('columndump2', models.CharField(blank=True, db_column='columnDump2', max_length=1000, null=True)),
                ('columndump3', models.CharField(blank=True, db_column='columnDump3', max_length=1000, null=True)),
                ('columndump4', models.CharField(blank=True, db_column='columnDump4', max_length=1000, null=True)),
                ('columndump5', models.CharField(blank=True, db_column='columnDump5', max_length=1000, null=True)),
                ('columndump6', models.CharField(blank=True, db_column='columnDump6', max_length=1000, null=True)),
                ('columndump7', models.CharField(blank=True, db_column='columnDump7', max_length=1000, null=True)),
                ('columndump8', models.CharField(blank=True, db_column='columnDump8', max_length=1000, null=True)),
                ('columndump9', models.CharField(blank=True, db_column='columnDump9', max_length=1000, null=True)),
                ('columndump10', models.CharField(blank=True, db_column='columnDump10', max_length=1000, null=True)),
                ('columndump11', models.CharField(blank=True, db_column='columnDump11', max_length=1000, null=True)),
                ('columndump12', models.CharField(blank=True, db_column='columnDump12', max_length=1000, null=True)),
                ('columndump13', models.CharField(blank=True, db_column='columnDump13', max_length=1000, null=True)),
                ('columndump14', models.CharField(blank=True, db_column='columnDump14', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'magic44_data_capture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44ExpectedResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField()),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('row_hash', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'magic44_expected_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44LogQueryErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField(blank=True, null=True)),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('query_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('error_code', models.CharField(blank=True, max_length=5, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'magic44_log_query_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44RowCountErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('step_id', models.IntegerField()),
                ('answer_total', models.BigIntegerField(blank=True, null=True)),
                ('result_total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'magic44_row_count_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44TableNameLookup',
            fields=[
                ('query_id', models.IntegerField(primary_key=True, serialize=False)),
                ('table_or_view_name', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'magic44_table_name_lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44TestCaseDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_step_id', models.IntegerField(blank=True, null=True)),
                ('number_of_steps', models.IntegerField(blank=True, null=True)),
                ('query_label', models.CharField(blank=True, max_length=20, null=True)),
                ('query_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scoring_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'magic44_test_case_directory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Magic44TestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField()),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('row_hash', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'magic44_test_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.CharField(db_column='personID', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeid', models.CharField(db_column='routeID', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airlineid', models.OneToOneField(db_column='airlineID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight_manager.airline')),
                ('tail_num', models.CharField(max_length=50, unique=True)),
                ('seat_capacity', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('plane_type', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenanced', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('neo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'airplane',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('personid', models.OneToOneField(db_column='personID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight_manager.person')),
                ('miles', models.IntegerField(blank=True, null=True)),
                ('funds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'passenger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerVacations',
            fields=[
                ('personid', models.OneToOneField(db_column='personID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight_manager.person')),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'passenger_vacations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('personid', models.OneToOneField(db_column='personID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight_manager.person')),
                ('taxid', models.CharField(db_column='taxID', max_length=50, unique=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pilot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('routeid', models.OneToOneField(db_column='routeID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight_manager.route')),
                ('sequence', models.IntegerField()),
            ],
            options={
                'db_table': 'route_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PilotLicenses',
            fields=[
                ('personid', models.OneToOneField(db_column='personID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flight_manager.pilot')),
                ('license', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pilot_licenses',
                'managed': False,
            },
        ),
    ]
